name = "Poisson2D"
uuid = "16c2e835-a2ae-4baa-aa1f-55e1f01f8ce2"
authors = ["Gideon Simpson <gideon.simpson@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
