name = "Heat1D"
uuid = "fb2540d4-95fa-40eb-884c-381159605f21"
authors = ["Gideon Simpson <gideon.simpson@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
